# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-06 07:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20170106_0006'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
