# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-06 11:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='point',
            field=models.BigIntegerField(default='0'),
        ),
    ]
